language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: fEToRf/keW1Wt8kwZa2iuU4FfqhYx6CRRVX7Ozq/CCXcfS/yZ8rWI+X+KOPhtDwUP/y/Hk7nUT99qkrPfDgEMNxxPc2I3IfAUchyQhUhLRfn+rbr+ydlXmNENjj0SKsX88vh2OMUStyDLKBYxisE/xPILq77dVTHL3k/lCgyhzBeoF9Mct580TZYYOjpWCBOoSOmjh6ojVMl/EjqrNgQL4AkuMS8QwrlaASTb8kR0va/eIlTrAUvUeOIOGG3HLZ5T5qOaVZ6ifwjDAyNlHBMa5dEwcfybIQ/ScfNZefKbv+u8lFG+bRSmydCneddZsuCV8PApPq2RLrbw7gWx7dHbR8rIsbbSnFvsuYN96/0veiaYyLdENmrrs8npEILerF8wXSJFlDU+wbf2cfDC362unDaonbdozgC2wXLaHpt8wT64nkSmG9vNv7E9kS2FOWjuGp892/JlSJ2g4PX5XHtvIrz/T9TbCtDKn5UsbRCPQeYpp3HuwF0Qjz4TBHxqDOnUqYEh3l5Bpoi2rvHiVgr/1Xp5kB0o9g/GmbqQrMQ1ni1xKite9LpBQY/B99NVJkg6KCTGRZnPTF/3JzGI3sgLQ0A/MW6RTd7/SNSFYXoNTVAlFNhxARXUWUvQSC8Yew4axQbxJzTe/Gawelq+I1s2efm9qc5jO1NCpzn3QX8DsE=
  app: travel-buddy-turing
  on:
    repo: antoniojking/travel_buddy_fe
    branch: main
env: 
before_install:
- yes | gem update --system --force
- gem install bundler
