language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: bs0WvYvomcqLHgusaPfMw00GfVUluDRO1cdXKEQX8A9ZCRfwzIEJeX+bJZ8Wn8Y0b/vdZxlqmoA2xh64PaxtbMxkbAwwr6zQqNPR6Ze/b5KKO8fDwcyeYFlduhQr7T+fuF5cSjada49OHRYXWWGudPRAuDSjYYp2MQgYWqSbzM7T6KtaQEHwH557hV+zQm75FCg6kpEmuTITYlPzmnhpWfKjv2Yb0NNBAqJyGceXIM5hV+B2F7EPm3uJv+op3/8NqCLzLqMqQGq7kUk3BUT1WSVBcj9HZSgNOt2FLpe8vGuP08vmWnlkzvKa/r3N9qPp2hcJ7Jky/OLOnhgltwnGlk2ApXgeQP66CLEYz15raItvtERWy5RxzFypqOsNr46eM0NqF4EIeT06PtjJGSvK7eXww3RZXhX0iWRdgNFYau4dmXJdG+3yI7JLPomVVQtDvGfhs5LoEQDm1g/2VN9OTWnZYcojW5csTDTqnWPkxGKJmpfrfV44BHnlHJBBmkkW8qbtJJgXCSHewRHXRI5KaoWR/bcRrwAKzzwn/8VauQM6kj7XAlPMndvxj8gBRVlp+y6nCZXcRI/gffGRkLIfwGBFtaCC8PWk71LUmFNDp/EaEafMX1lzki/e6KmBuGofUZoCIDyPq9weQtY+SODHFaJWrJp3Aog7v+yCmhs2Y9A=
  app: travel-buddy-turing
  on:
    branch: main
env: 
before_install:
- yes | gem update --system --force
- gem install bundler
